name: cliinapp
description: "CliinApp — Application civic-tech de signalement d'insalubrité. Ville pilote : San-Pedro, Côte d'Ivoire."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_localizations:
  sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - google_fonts/
